CREATE TABLE USUARIO (
   IDUSUARIO SERIAL,
   NOME VARCHAR (100),
   SENHA VARCHAR (45),
   EMAIL VARCHAR (100),
   ADMIN BOOLEAN,
   SITUACAO CHAR (1),
   PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE PRODUTO (
   IDPRODUTO SERIAL,
   DESCRICAO VARCHAR (100),
   PRIMARY KEY (IDPRODUTO)
);


CREATE TABLE LISTA (
   IDLISTA SERIAL,
   NOME VARCHAR (100),
   DATA TIMESTAMP WITHOUT TIME ZONE,
   SITUACAO CHAR (1),
   FK_IDUSUARIO INT,
   PRIMARY KEY (IDLISTA),
   FOREIGN KEY (FK_IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);

CREATE TABLE ITENSLISTA (
   IDITENSLISTA SERIAL,
   IDPRODUTO INT,
   PRODUTO VARCHAR (100),
   QTDEREQUERIDA DECIMAL (10,2),
   QTDECOMPRADA DECIMAL (10,2),
   VALORITEM DECIMAL (10,2),
   SITUACAOITEM CHAR (1),
   FK_IDUSUARIO INT,
   FK_IDLISTA INT,
   PRIMARY KEY (IDITENSLISTA),
   FOREIGN KEY (FK_IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
   FOREIGN KEY (FK_IDLISTA) REFERENCES LISTA (IDLISTA)
);

